---

- name: Configure game servers
  gather_facts: false
  hosts: game
  roles:
    - configure-game

- name: Configure matchmaking servers
  gather_facts: false
  hosts: matchmaker
  roles:
    - configure-matchmaker
