---
# Server Deployment
-

- name: stop harvard
  service:
    name: harvard
    state: stopped 

- name: copy server executable
  copy:
    src: ../../Build/{{ exe_name }}
    dest: /home/{{ server_user }}/{{ exe_name }}
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: '0700'
  notify:
    - reload systemctl daemon
    - restart harvard

- name: synchronize server data
  synchronize:
    src: ../../Build/{{ exe_name }}_Data
    dest: /home/{{ server_user }}/
    delete: yes
  notify:
    - reload systemctl daemon
    - restart harvard

- name: set data ownership
  command: chown -R {{ server_user }}:{{ server_user }} /home/{{ server_user }}/{{ exe_name }}_Data
  args:
    warn: no
